### ISSUE TITLE
Latest version missing in F-Droid

### ISSUE THREAD

**Issue by Hainish** [dougkeen/BartRunnerAndroid#17]
The latest version in F-Droid is 2.2.6 (Added on Oct 31, 2015) as opposed to the Play Store, which has 2.2.10

https://f-droid.org/packages/com.dougkeen.bart/
https://play.google.com/store/apps/details?id=com.dougkeen.bart&hl=en

**Comment by rpdelaney** [comment]
Annoying. Has this app been abandoned? :(

**Comment by dougkeen** [comment]
F-Droid does their own builds on their side by pulling this source code directly, and I don't really have any control over that. It's possible something changed in the source that is no longer compatible with their build system, but I don't have the bandwidth to look into that right now. If someone figures it out and submits a pull request, I'd be happy to look it over.

**Comment by bwitt** [comment]
I see the latest version (2.2.18) on f-droid now (https://f-droid.org/packages/com.dougkeen.bart/) , so I think this can be closed.
