### ISSUE TITLE
App shows cancelled trains

### ISSUE THREAD

**Issue by mbbush** [dougkeen/BartRunnerAndroid#30]
At some point recently Bart made a semantic change to their API to make it also return cancelled trips alongside real ones. 

From http://api.bart.gov/docs/etd/etd.aspx
> `<cancelflag>` indicates a scheduled ETD that has been cancelled and is not in service.
> `<dynamicflag>` indicates an unscheduled ETD that has been added to service.

The Bart runner app doesn't know about this new field, so it shows the cancelled trains alongside real ones.

I could probably implement a PR which filters them out of the API response entirely. A better solution would probably be to show them in ~strikethrough~, but that's not something I have a clear idea how to do.

**Comment by dougkeen** [comment]
Great find! Yeah, I'd definitely welcome a PR if you have time to knock it out.

**Comment by mbbush** [comment]
Looks like you took care of it in 9ecede06, far better than I could have. I was just browsing through the code to see about my idea for a janky solution when I saw that you'd already done it. Thanks!
